### ISSUE TITLE
Błędy gry

### ISSUE THREAD

**Issue by olovik** [szmurlor/logo-worlds#1]
Znalazłem 2 błędy w grze:
-pierwszy dotyczy logowania, trzeba szybko wpisać dwie cyfry kodu świata qwerty_XY, bo inaczej strona otwiera świat qwerty_X.
-drugi dotyczy resetowania świata. Po resecie świata i odświeżeniu strony w celu wyczyszczenia mapy, czołg pojawia się na losowym polu, które się odkrywa, lecz wykonanie jakiegokolwiek ruchu teleportuje go na oryginalny spawn (ten, gdzie czołg znajduje się po pierwszym wygenerowaniu mapy), dalej program działa poprawnie, lecz to losowe pole pozostaje odkryte.
![Przechwytywanie](https://user-images.githubusercontent.com/73238992/102498575-70f19380-407a-11eb-9e86-f933328bb8b9.PNG)

**Comment by szmurlor** [comment]
Bardzo dziękuję za zgłoszenie. Zaraz na to zerknę.

Następnym razem, gdy zgłoszenie dwóch błędów lepiej podzielić jest na dwa osobne zgłoszenia (issues). Wtedy twórcy systemu gdy rozwiążą jeden problem to mogą go sobie zonaczyć - Solved, i Closed. Tak aby zamknąc issue trzeba rozwiązać oba :-)

**Comment by szmurlor** [comment]
Dziękuję za zgłoszenie - oba błędy powinny być rozwiązane. Proszę odświeżyć grę: SHIFT+F5 i sprawdzić. Jak Pan stwierdzi, że błędy zostały usunięte (proszę o komentarz tutaj) to zamknę issue.

**Comment by olovik** [comment]
Działa znakomicie!
