### ISSUE TITLE
Błąd gry - Po resecie mapy zawsze trzeba odświeżyć stronę

### ISSUE THREAD

**Issue by olovik** [szmurlor/logo-worlds#2]
Bawiłem się jeszcze dzisiaj czołgiem i niestety trafiłem na kolejny błąd.
Po resecie mapy zawsze trzeba odświeżyć stronę, w przeciwnym przypadku mapę można odkryć nawet w jednym ruchu.
![image](https://user-images.githubusercontent.com/73238992/102531311-5df2b980-40a2-11eb-9b92-ff4a3c17af56.png)
Pozdrawiam
Wojciech Pachulski
in-game bug engineer
CDPR

**Comment by szmurlor** [comment]
in-game beta tester 💯 ! Dziękuję za uwagę. Sugeruję w temacie issue podawać czego dotyczy. Np. w tym przypadku pasowałoby: 'Po resecie mapy zawsze trzeba odświeżyć stronę'

Zerknę na to na pewno :-) Dzięki jeszcze raz za informację :-)

**Comment by szmurlor** [comment]
Dzięki! Poprawione. Problem polegał na tym, że po resecie metoda callback reagująca na wciśnięcie klawisza na klawiaturze przechowywała referencję do starej tablicy (sprzed resetu).
