### ISSUE TITLE
Błędna definicja MoveResponse

### ISSUE THREAD

**Issue by PawelBlaszkiewicz** [szmurlor/logo-worlds#3]
Po wejściu na stronę http://edi.iem.pw.edu.pl:30000/ przeglądałem modele i zauważyłem, że zawartości Explore i WorldInfo są identyczne.
![sfedsfcf](https://user-images.githubusercontent.com/73287180/102697585-1c474780-4237-11eb-8218-45872dab50ab.jpg)
Pozdrawiam 
Paweł Błaszkiewicz

**Comment by szmurlor** [comment]
Dzięki błąd poprawiony. Problem polegał na konflikcie nazw w definicje zwracanego pola: `fields` z biblioteką `flask-restx` służącą do generowania definicji. Teraz zwracane pole przez nasze API nazywa się `list` zamiast fields.:

Czyli zamiast:

```json
{
  "status": "string",
  "error": "string",
  "payload": {
    "fields": [
      {
        "x": 0,
        "y": 0,
        "type": "string"
      }
    ]
  }
}
```

teraz zwracam:

```json
{
  "status": "string",
  "error": "string",
  "payload": {
    "list": [
      {
        "x": 0,
        "y": 0,
        "type": "string"
      }
    ]
  }
}
```
